name: "Notification Messages"

description: "Get the notification message"

inputs:
  format:
    description: 'The output format. Possible values: "markdown", "plaintext".'
    required: false
    default: plaintext
  event-name:
    description: "The name of the webhook event."
    required: false
    default: ${{ github.event_name }}
  event-json:
    description: "The webhook event converted to JSON."
    required: false
    default: ${{ toJSON(github.event) }}

outputs:
  message:
    description: "The notification message"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.event-name }}
    - ${{ inputs.event-json }}
    - ${{ inputs.format }}
